# -*- mode: python ; coding: utf-8 -*-

import os
import sys

PROJECT_ROOT = os.path.dirname(os.path.abspath(SPEC))

datas = [
    (os.path.join(PROJECT_ROOT, 'scripts'), 'scripts'),
    (os.path.join(PROJECT_ROOT, 'agents'), 'agents'),
]

hiddenimports = [
    'PyQt5',
    'PyQt5.QtWidgets',
    'PyQt5.QtCore',
    'PyQt5.QtGui',
    'netmiko',
    'paramiko',
    'requests',
    'json',
    'backup_all_config',
    'network_inspect',
    'run_trouble_cmd',
    'src',
    'src.core',
    'src.core.config_generator',
    'src.core.key_manager',
    'src.core.secure_config',
    'src.core.logger',
    'src.core.device_manager',
    'src.core.crypto_utils',
    'src.core.local_audit_engine',
    'src.core.local_diagnostic_engine',
    'src.ui',
    'src.ui.main_window',
    'src.ui.system_settings_page',
    'src.ui.project_manager_page',
    'src.ui.ops_toolbox_page',
    'src.ui.single_device_page',
    'src.ui.ai_analysis_page',
    'src.ui.security_dialogs',
    'src.ui.device_form_dialog',
    'src.ui.device_discovery_dialog',
    'src.ui.device_template_dialog',
    'src.ui.history_dialog',
    'src.ui.config_pages',
    'src.ui.config_pages.base_config_page',
    'src.ui.config_pages.ruijie',
    'src.ui.config_pages.ruijie.access_switch_config',
    'src.ui.config_pages.ruijie.core_switch_config',
    'src.ui.config_pages.ruijie.router_config',
    'src.ui.config_pages.ruijie.ac_config',
    'src.ui.config_pages.huawei',
    'src.ui.config_pages.huawei.access_switch_config',
    'src.ui.config_pages.huawei.core_switch_config',
    'src.ui.config_pages.huawei.router_config',
    'src.ui.config_pages.huawei.ac_config',
    'src.ui.config_pages.h3c',
    'src.ui.config_pages.h3c.access_switch_config',
    'src.ui.config_pages.h3c.core_switch_config',
    'src.ui.config_pages.h3c.router_config',
    'src.ui.config_pages.h3c.ac_config',
    'src.ui.config_pages.cisco',
    'src.ui.config_pages.cisco.access_switch_config',
    'src.ui.config_pages.cisco.core_switch_config',
    'src.ui.config_pages.cisco.router_config',
    'src.ui.config_pages.cisco.ac_config',
    'src.utils',
    'src.utils.resource_path',
    'src.utils.validators',
    'src.utils.file_operators',
    'cryptography',
    'cryptography.hazmat.primitives.ciphers.aead',
    'cryptography.hazmat.primitives.kdf.pbkdf2',
    'cryptography.hazmat.primitives.hashes',
    'certifi',
]

a = Analysis(
    ['main.py'],
    pathex=[PROJECT_ROOT, os.path.join(PROJECT_ROOT, 'scripts')],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'chardet.pipeline.orchestrator__mypyc',
        'chardet.pipeline.ascii__mypyc',
        'chardet.pipeline.confusion__mypyc',
        'chardet.pipeline.escape__mypyc',
        'chardet.pipeline.magic__mypyc',
        'chardet.pipeline.statistical__mypyc',
        'chardet.pipeline.structural__mypyc',
        'chardet.pipeline.utf1632__mypyc',
        'chardet.pipeline.utf8__mypyc',
        'chardet.pipeline.validity__mypyc',
        'PySide6',
        'PySide6.QtCore',
        'PySide6.QtGui',
        'PySide6.QtWidgets',
        'tzdata',
        'torch',
        'tensorflow',
        'keras',
        'sympy',
        'nltk',
        'spacy',
        'pygame',
        'opencv-python',
        'cv2',
        'PIL',
        'matplotlib',
        'scipy',
        'sklearn',
        'scikit-learn',
        'bokeh',
        'dash',
        'plotly',
        'seaborn',
        'kivy',
        'jupyter',
        'sqlalchemy',
        'flask',
        'django',
        'fastapi',
        'beautifulsoup4',
        'bs4',
        'selenium',
        'transformers',
        'tokenizers',
        'sacremoses',
        'emoji',
        'lxml',
        'pandas',
        'openpyxl',
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='NetworkConfigGenerator',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)